name: General Question
description: Ask a question about UMS setup, usage, or development.
title: "[QUESTION] "
labels: ["question", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help!
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What do you need help with?
      placeholder: "e.g., How do I set up the database for UMS?"
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Provide background or details.
      placeholder: "e.g., I'm trying to run the app locally and getting a MySQL connection error."
  - type: input
    id: environment
    attributes:
      label: Environment (if applicable)
      description: Your setup details.
      placeholder: "e.g., Python 3.10, MySQL 8.0, Ubuntu 22.04"
